# Generated by Django 5.2.2 on 2025-06-17 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Challenge', '0002_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobbies',
            name='hobby_image',
            field=models.CharField(default='https://th.bing.com/th/id/OIP.kcnWCTmXz1gblj3emSQBDAHaHK?rs=1&pid=ImgDetMain', max_length=500),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_image',
            field=models.CharField(default='https://th.bing.com/th/id/OIP.0peFLquqi8FFO0e9R3aVyQHaFj?rs=1&pid=ImgDetMain', max_length=500),
        ),
    ]
