# Generated by Django 5.2.2 on 2025-06-22 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Challenge', '0003_hobbies_hobby_image_portfolio_portfolio_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=200)),
                ('contact_email', models.CharField(max_length=200)),
                ('contact_message', models.CharField(max_length=500)),
            ],
        ),
    ]
